// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "ar" | "en";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
   * @param {string} name
   */
  HI: RequiredParams<"name">;
  /**
   * Engine
   */
  MOHARIK: string;
};

export type TranslationFunctions = {
  /**
   * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
   */
  HI: (arg: { name: string }) => LocalizedString;
  /**
   * Engine
   */
  MOHARIK: () => LocalizedString;
};

export type Formatters = {};
